#!/usr/bin/perl -w

use esmith::Build::CreateLinks  qw(:all);

safe_symlink("/etc/e-smith/templates-default/template-begin-php", "root/etc/e-smith/templates/etc/dokuwiki/local.protected.php/template-begin");
safe_symlink("/etc/e-smith/templates-default/template-end-php", "root/etc/e-smith/templates/etc/dokuwiki/local.protected.php/template-end");

my $event = "nethserver-dokuwiki-update";

event_actions($event, 
             'initialize-default-databases' => '00');

templates2events("/etc/httpd/conf.d/zzz_dokuwiki.conf",  $event);
templates2events("/etc/dokuwiki/local.protected.php",  $event);
templates2events("/etc/httpd/conf.d/default-virtualhost.inc",  $event);

event_services($event, 'httpd' => 'restart');

#case dc or directory installed after
templates2events("/etc/dokuwiki/local.protected.php",  qw (
    nethserver-sssd-save 
    nethserver-dc-update 
    nethserver-directory-update
    ));

my $event = 'trusted-networks-modify';
templates2events("/etc/httpd/conf.d/zzz_dokuwiki.conf",  $event);
event_services($event, 'httpd' => 'reload');

my $event = 'certificate-update';
templates2events("/etc/httpd/conf.d/zzz_dokuwiki.conf",  $event);
event_services($event, 'httpd' => 'reload');

