#!/usr/bin/perl -w

use esmith::Build::CreateLinks  qw(:all);

safe_symlink("/etc/e-smith/templates-default/template-begin-php", "root/etc/e-smith/templates/etc/dokuwiki/local.protected.php/template-begin");
safe_symlink("/etc/e-smith/templates-default/template-end-php", "root/etc/e-smith/templates/etc/dokuwiki/local.protected.php/template-end");

my $event = "nethserver-dokuwiki-update";

event_actions($event, 
             'initialize-default-databases' => '00');

templates2events("/etc/httpd/conf.d/dokuwiki.conf",  $event);
templates2events("/etc/dokuwiki/local.protected.php",  $event);
templates2events("/etc/httpd/conf/httpd.conf",  $event);

event_services($event, 'httpd' => 'reload');

my $event = 'trusted-networks-modify';
templates2events("/etc/httpd/conf.d/dokuwiki.conf",  $event);
event_services($event, 'httpd' => 'reload');
